version: "3.7"

services:

  nodeapp:
    image: nodeapp:v1
    networks:
      - letsplay
    ports:
      - "3000:3000"
    healthcheck:
       test: ["CMD", "curl", "-f", "http://localhost:3000"]
       interval: 30s
       timeout: 20s
       retries: 3
       start_period: 50s
    deploy:
      mode: replicated
      replicas: 1
      labels:
         - traefik.frontend.rule=Host:node.local
         - traefik.docker.network=traefik
         - traefik.port=80
         - traefik.enable=true
      update_config:
         parallelism: 1
         delay: 5s
         monitor: 10s
         failure_action: rollback
      rollback_config:
         order: start-first
      restart_policy: 
         condition: on-failure
         delay: 5s
         max_attempts: 2
         window: 30s

networks:
   letsplay:
      driver: overlay
      external: true

   traefik:
      driver: overlay
      external: true
