version: "3.6"

services:

  nodeapp:
    environment:
    image: nodeapp:1
    networks:
      - letsplay
    ports:
      - "3000:3000"
    deploy:
      mode: replicated
      replicas: "${CORES}"
