version: "3.7"

services:

  nodeapp:
    image: nodeapp:v1
    networks:
      - letsplay
    ports:
      - "3000:3000"
    healthcheck:
       test: ["CMD", "curl", "-f", "http://localhost:3000"]
       interval: 30s
       timeout: 20s
       retries: 3
       start_period: 50s
    deploy:
      mode: replicated
      update_config:
         parallelism: 1
         delay: 10s
      replicas: 1
      restart_policy: on-failure

networks:
   letsplay:
      driver: overlay
      external: true

   traefik:
      driver: overlay
      external: true
