version: "3.3"

services:
  traefik:
    image: chmodrs/traefik:1.7-alpine-curl
    healthcheck:
       test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
       interval: 30s
       timeout: 20s
       retries: 3
    ports:
      - 80:80
      - 8080:8080
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/log:/var/log/
    configs:
      - source: traefik-config
        target: /etc/traefik/traefik.toml
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
         condition: on-failure
         delay: 5s
         max_attempts: 2
         window: 30s

networks:
  traefik:
    driver: overlay
    external: true

configs:
  traefik-config:
    file: config.toml
